### ISSUE TITLE
diskpart shrinking regex issue: "Error in shrinking! Couldn't find the max number of reclaimable bytes!"

### ISSUE THREAD

**Issue by isrc** [grnet/snf-image-creator#53]
Hi,
I'm using snf-image-creator_0.9next~772~ff4fcaf~7b4b66f-1~jessie_all.deb on a up to date debian jessie host 

Whenever i try to generate a snf-image of a KVM VM of Windows Server 2012 R2 (French Edition) thanks to snf-mkimage, the process fails with this error: "Error in shrinking! Couldn't find the max number of reclaimable bytes!" 
This is the same regex issue as the one identified in this post https://groups.google.com/d/msg/synnefo/C1-tJLrIikI/3knhhLdfN6AJ. 
Indeed:
  - the culprit regex is https://github.com/grnet/snf-image-creator/blob/develop/image_creator/os_type/windows/__init__.py#L411
  - because, in the french edition of Windows, the output of the "SHRINK QUERYMAX" diskpart command is: `DISKPART> shrink querymax`

`Le nombre maximal d'octets récupérables est : 66 GB (68226 Mo)`
  - As one can see, the regex is looking for a "B" (aka Byte) between the parenthesis but in FR, the unit character for byte is "o" (as in Go, Mo, Ko instead of GB, MB, KB in english)

And i can confirm that by replacing the last "B" char by "o", snf-mkimage works as expected...but, obviously, that's not a correct fix :)

HTH,
Thanks !

PS: BTW, the current winexe_1.1~pre1~2912528a63b4a775dbbc64e393fcecb41682b6b8-3~jessie_amd64.deb package don't install on the latest Jessie because of dependence issue with the latest samba-libs package

**Comment by skalkoto** [comment]
Hello,

I was out of reach for some time now. First of all thank you for the detailed bug report. I've recompiled winexe. It sould work with the latest jessie updates. Considering the shrinking issue, I couldn't find a way to get the querymax value without parsing messages and this is why we have this mess. I'll add the 'o' character in the regular expression to fix this. I cannot think of something better.

**Comment by isrc** [comment]
Hi Nikos,
Fantastic, thank you for taking the time to fix both of those issues so quickly :+1: ! 
For the regex issue, i'm just wondering if looking up only the first letter of the unit should be enough (aka grepping on "M", "K"...) ?

And thanks for the snf-image{,-creator} software suite: it's an invaluable tool for those of us running Ganeti cluster

**Comment by skalkoto** [comment]
and what if the qeurymax returns bytes?

**Comment by skalkoto** [comment]
Well I did some testing and it seems I don't need the querymax thing at all. If i simply execute "shrink", the command will reclaim the maximum amount of space possible. If I then do "extend size=100", 100MB will be given to the device back. This way, I can simulate the old behavior without having to read the output of the command. I think this will fix the issue once and for all.
