### ISSUE TITLE
Standalone option

### ISSUE THREAD

**Issue by klemens-u** [grnet/snf-image-creator#58]
Hello, I discovered snf-image-creator via snf-image for ganeti. snf-image-creator looks really great, but it was a big bummer to find out it works only with the "cloud". 

Is there any trick to simply output the created image into a local directory?

If not I'd like to submit this idea as enhancement.

**Comment by skalkoto** [comment]
If you are using `snf-mkimage`  command you may define the -o option. If you are using the dialog based version `snf-image-creator` try expert mode and use the "Extract" option after "Customize". Check here for the documentation:
https://www.synnefo.org/docs/snf-image-creator/latest/

**Comment by klemens-u** [comment]
Thanks!
