### ISSUE TITLE
Fix setting kernel parameter to enable legacy interface names

### ISSUE THREAD

**Issue by kasimon** [grnet/snf-image-creator#64]
Please "steal" the following fix:

https://github.com/itminedu/snf-image-creator/commit/a0677d50ee3b754be2982f3baae196aea6b29c6d

**Comment by irregulator** [comment]
Hi,

can you please explain what is the issue and what is your proposal?

**Comment by kasimon** [comment]
Sorry, I was misguided by the fact that there is no 0.11.2 release in this repository so i was mistakenly assuming the issue was not fixed here.
